### ISSUE TITLE
[Fullstack] Fullstack developer looking for another developers

### ISSUE THREAD

**Issue by mqshaikh8** [devchat-dev/devhacks#2]
## I'm good at these skills

- React
- Rails

# I want to get better at these skills

- Python
- Node

# I'm looking for a partner who...

Someone who has an artistic side and can code good too

**Comment by BobocG211096** [comment]
Hi, 

I am a passionate Java developer with 3 years experience in building the backend of the applications, so if you are intersted, please let me know and we will hear on video for getting to know better.

**Comment by kaggwachristopher** [comment]
hi @mqshaikh8 I am good at nodeJS and Django(Python)... will be nice to learn rails from you too..
